language: android
android:
  components:
    - build-tools-21.1.2
    - android-25
    - sys-img-armeabi-v7a-google_apis-25
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8
# Emulator Management: Create, Start and Wait
before_script:
  - emulator -avd test -no-skin -no-audio -no-window &
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
  - android list target
  - ant debug install
