language: android
android:
  components:
    - build-tools-21.1.2
    - android-3
env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

script:
  - android list target
  - ant debug install
